### 1. Reference
- http://www.numpy.org/
- http://aikorea.org/cs231n/python-numpy-tutorial/

### 2. Install
- pip3 install numpy

### 3. Make
- array
- reshape
- index
- zeros
- ones
- eye
- like
- empty
- arange
- linespace, logspace
- rand, randn
- stack
- concatenate
- split
- sort

In [1]:
import numpy as np

#### 1) Array
- ndim : 행렬의 차원
- shape : 행렬의 모양

In [2]:
# 1차원 배열 (vector)
array = np.array([0,1,2,3,4,5])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [3]:
# 2차원 배열 (1*3 matrix)
array = np.array([[0],[1],[2]]) 
print(array)

[[0]
 [1]
 [2]]


In [4]:
# 2차원 배열 (2*3 matrix)
array = np.array([
    [0,1,2],
    [3,4,5] ]) 

print(array)

[[0 1 2]
 [3 4 5]]


In [5]:
# 3차원 배열 (2*3*4 matrix)
array = np.array([
    [[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]],
    [[0,1,2,3],
     [4,5,100,7],
     [8,9,10,11]]
]) 

print(array) # martrix
print(array.ndim) # 차원 수
print(array.shape) # matrix 모양

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[  0   1   2   3]
  [  4   5 100   7]
  [  8   9  10  11]]]
3
(2, 3, 4)


** 2) Reshape **: 행렬의 모양을 재정의

In [6]:
na = np.array([1,2,3,4,5,6,7,8]) # 1*8차원 matrix
na.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
rna = np.reshape(na,(4,2)) # na를 4*2 matrix로 재정의
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
# 전치행렬 (행과 열을 바꿈)
rna.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

#### 3) Index
- 행렬의 특정 위치 데이터 값 가져오기
- 행렬 자르기
- index는 0부터 시작

In [9]:
array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[  0,   1,   2,   3],
        [  4,   5, 100,   7],
        [  8,   9,  10,  11]]])

In [10]:
print(array[1][1][2]) # 첫번째 차원, 첫번째 행, 두번째 열을 가져오기
print(array[1,1,2])

100
100


In [11]:
result = array[1:,1:,2:] # 첫번째 차원부터 끝 차원까지, 첫번째 행부터 끝행까지, 두번째 열부터 끝열까지 가져오기
print(result) # 결과값
print(result.ndim) # 결과가 2차처럼 보이지만 아직 3차원
print(result.shape) # 따라서 (1, 2, 2)로 나타남

[[[100   7]
  [ 10  11]]]
3
(1, 2, 2)


** 4) Zeros **: 행렬을 만들고 안에 0으로 채워 넣음

In [12]:
# 1차원
z = np.zeros(5)
print(z)
print(z.ndim, z.shape)

[0. 0. 0. 0. 0.]
1 (5,)


In [13]:
# 2차원 (2*3)
z = np.zeros((2,3))
print(z)
print(z.ndim, z.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
2 (2, 3)


In [14]:
# 3차원 (2*3*4)
z = np.zeros([2,3,4])
print(z)
print(z.ndim, z.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3 (2, 3, 4)


**5) Ones** : 행렬을 만들고 안에 1을 채워 넣음

In [15]:
# 3차원 (2*3*4)
o = np.ones([2,3,4])
print(o)
print(o.ndim, o.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4)


**6) Eye, Identity ** : 단위 행렬 데이터를 생성

In [16]:
# eye
np.eye(3); 

In [17]:
# identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

** 7) Like** : 행렬 안에 있는 모든 데이터를 0이나 1로 바꿀수 있다.

In [18]:
# np.ones_like
z # 모든 원소가 0인 matrix
ls = np.ones_like(z) # 모든 원소를 1로 변환
print(ls)
print(ls.ndim, ls.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4)


In [19]:
# np.zeros_like
o # 모든 원소가 1인 matrix
ls = np.zeros_like(o) # 모든 원소를 0로 변환
print(ls)
print(ls.ndim, ls.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3 (2, 3, 4)


#### 8) Empty
- 빈 행렬을 생성 (실제로 빈데이터가 아니라 더미 데이터가 들어감)
- 더미 데이터 : 용량을 맞추기 위해 끼워넣는 의미없는 파일

In [20]:
a = np.empty((2,2)) # 실제 값이 있음을 확인
print(a)

[[5.e-324 5.e-324]
 [5.e-324 0.e+000]]


#### 9) Arange
- range와 같음
- 하지만 큰데이터에서 range 보다 속도가 빠름

In [21]:
# range와 arange의 속도 비교
size = int(1E6) # 앞에 숫자 1 뒤에 0이 6개 있다는 의미 -> size = 1,000,000
%timeit for x in range(size): x ** 2
%timeit for x in np.arange(size): x ** 2

384 ms ± 12.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
213 ms ± 6.93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [22]:
np.arange(10) # 0부터 9까지 출력

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(5,10) # 5부터 10까지 출력

array([5, 6, 7, 8, 9])

In [24]:
np.arange(2,10,3) # 2부터 10까지 3 간격으로 출력

array([2, 5, 8])

In [25]:
np.arange(10,1,-2) # 10부터 1까지 -2 간격으로 출력

array([10,  8,  6,  4,  2])

**10) Linspace, Logspace** : 구간을 기준으로 일정하게 나누기

In [26]:
# linsapce : 실수
np.linspace(0, 100, 5) # 0과 100을 포함해 일정한 간격으로 5개의 숫자를 출력 (끝 값도 포함되니까 주의)

array([  0.,  25.,  50.,  75., 100.])

In [27]:
# logspace : 로그값
print(np.logspace(2, 4, 3)) # log2, log3, log4
print(np.logspace(2, 3, 3)) # log2, log2.5, log3

[  100.  1000. 10000.]
[ 100.          316.22776602 1000.        ]


#### 11) Random
- seed
- rand (uniform)
- randn (gaussian)
- randint
- shuffle
- choice

**(1) Seed** :  어떤 특정한 시작 숫자를 정해주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성

In [28]:
np.random.seed(0) # 난수 셋팅

**(2) Rand (Uniform)** : 균등분포 난수 발생

In [29]:
# uniform 으로 난수 발생 (균등분포)
rd = np.random.rand(5) 
print(rd)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [30]:
# matrix 생성
r = np.random.rand(2,3,4)
print(r)

[[[0.64589411 0.43758721 0.891773   0.96366276]
  [0.38344152 0.79172504 0.52889492 0.56804456]
  [0.92559664 0.07103606 0.0871293  0.0202184 ]]

 [[0.83261985 0.77815675 0.87001215 0.97861834]
  [0.79915856 0.46147936 0.78052918 0.11827443]
  [0.63992102 0.14335329 0.94466892 0.52184832]]]


**(3) Randn (gaussian)** : 정규분포 난수 발생

In [31]:
# gaussian 으로 난수 발생 (정규분포 - 0에 가까운수가 많이 나옴)
rdn = np.random.randn(5) 
print(rdn)

[-1.56349669 -0.56669762 -0.24214951  1.51439128 -0.3330574 ]


In [32]:
# matrix 생성
r = np.random.randn(2,3,4)
print(r)

[[[ 0.04736482  1.46274045  1.53502913  0.56644004]
  [ 0.14926509 -1.078278    1.39547227  1.78748405]
  [-0.56951726  0.17538653 -0.46250554 -1.0858006 ]]

 [[ 0.63973599 -0.38586334 -0.77576235  0.99571135]
  [-1.93320478  0.24853063 -0.03124534 -0.13947396]
  [-0.19065598  0.44863753 -0.99242977 -0.22593966]]]


**(4) Randint** : 정수 난수 발생

In [33]:
r1 = np.random.randint(0,10,(3,3)) # 0~9 까지 (3,3)행렬을 생성
r2 = np.random.randint(10, size=(3,3)) # 0~9 까지 (3,3)행렬을 생성
print(r1)
print(r2)

[[3 7 5]
 [5 0 1]
 [5 9 3]]
[[0 5 0]
 [1 2 4]
 [2 0 3]]


**(5) Shuffle** : 데이터의 순서 무작위로 바꿈

In [34]:
np.random.shuffle(r1)
r1

array([[5, 0, 1],
       [3, 7, 5],
       [5, 9, 3]])

**(6) Choice** : 각 원소에 확률을 부여해서 추출

In [35]:
# p의 확률로 range(5)를 10개 추출
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 3, 0, 2, 2, 2, 2, 2, 3])

In [36]:
# unique로 데이터의 유일한 값에 대한 리스트와 값의 갯수를 구할수 있다
index, count = np.unique(r, return_counts=True)
index, count

(array([-1.93320478, -1.0858006 , -1.078278  , -0.99242977, -0.77576235,
        -0.56951726, -0.46250554, -0.38586334, -0.22593966, -0.19065598,
        -0.13947396, -0.03124534,  0.04736482,  0.14926509,  0.17538653,
         0.24853063,  0.44863753,  0.56644004,  0.63973599,  0.99571135,
         1.39547227,  1.46274045,  1.53502913,  1.78748405]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1]))

** 12) Stack** : 행렬을 쌓는것과 같이 합치는 방법

In [37]:
# matrix 생성
na1 = np.arange(6)
na2 = np.arange(6,12)
print(na1, na1.shape)
print(na2, na2.shape)

[0 1 2 3 4 5] (6,)
[ 6  7  8  9 10 11] (6,)


In [38]:
na3 = np.stack((na1, na2)) # 행으로 쌓기
print(na3, na3.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


In [39]:
na3 = np.stack((na1, na2), axis=1) # 열로 쌓기
print(na3, na3.shape)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]] (6, 2)


In [40]:
# practice 1
ls = []
for i in range(5):
    print(range(7), i, i+3)
    print(range(7)[i:i+3])
    print(list(range(7)[i:i+3]), end="\n\n")
    ls.append(range(7)[i:i+3])    
ls

range(0, 7) 0 3
range(0, 3)
[0, 1, 2]

range(0, 7) 1 4
range(1, 4)
[1, 2, 3]

range(0, 7) 2 5
range(2, 5)
[2, 3, 4]

range(0, 7) 3 6
range(3, 6)
[3, 4, 5]

range(0, 7) 4 7
range(4, 7)
[4, 5, 6]



[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [41]:
# 수직으로 합치기
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [42]:
# 수평으로 합치기. 하지만 리스트가 됨, 다른 방법이 필요
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [43]:
# 수평으로 합치기
data = [list(range(7)[i:i+3]) for i in range(5) ] 
print(data)
np.stack(data, axis=1)

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [44]:
# practice 2
np.arange(5)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

#### 13) Concatenate (결합)

- 가로 결합은 열의 갯수가 같아야 함
- 세로 결합은 행의 갯수가 같아야 함

In [45]:
r1 = np.random.randint(10, size=(2,3))
print(r1) # matrix (2,3)

r2 = np.random.randint(10, size=(3,2))
print(r2) # matrix (3,2)

r3 = np.random.randint(10, size=(3,3))
print(r3) # matrix (3,3)

[[3 2 3]
 [4 1 2]]
[[9 1]
 [4 6]
 [8 2]]
[[3 0 0]
 [6 0 6]
 [3 3 8]]


**(1) 가로 결합**

In [46]:
# 가로 결합
np.concatenate([r1, r3], axis=0)

array([[3, 2, 3],
       [4, 1, 2],
       [3, 0, 0],
       [6, 0, 6],
       [3, 3, 8]])

**(2) 세로 결합**

In [47]:
# 세로 결합
np.concatenate([r2, r3], axis=1)

array([[9, 1, 3, 0, 0],
       [4, 6, 6, 0, 6],
       [8, 2, 3, 3, 8]])

#### 14) Split

In [48]:
r = np.arange(5,20)
r

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
r1 = np.split(r, [5]) # 앞에서 5번째를 기준으로 나눔
r1

[array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

In [50]:
# r1에는 나눈 데이터의 첫번째 데이터가 r2에는 나눈 데이터의 두번째 데이터가 들어감
r1, r2 = np.split(r, [5]) 
r1, r2

(array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [51]:
r1, r2, r3, r4, r5 = np.split(r, [2,4,6,8]) # 2,4,6,8을 기준으로 나눠 5개의 array 데이터가 생성
r1, r2, r3, r4, r5

(array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12]),
 array([13, 14, 15, 16, 17, 18, 19]))

**(1) Vsplit**: 행렬을 수평으로 나눔

In [52]:
r = np.random.randint(10, size=(4,6))
r

array([[8, 8, 2, 3, 2, 0],
       [8, 8, 3, 8, 2, 8],
       [4, 3, 0, 4, 3, 6],
       [9, 8, 0, 8, 5, 9]])

In [53]:
# 수평으로 2개씩 자름
r1, r2 = np.vsplit(r, [2])
print(r1)
print(r2)

[[8 8 2 3 2 0]
 [8 8 3 8 2 8]]
[[4 3 0 4 3 6]
 [9 8 0 8 5 9]]


**(2) Hsplit**: 행렬을 수직으로 나눔

In [54]:
# 수직으로 3개씩 자름
r1, r2 = np.hsplit(r, [3])
print(r1)
print(r2)

[[8 8 2]
 [8 8 3]
 [4 3 0]
 [9 8 0]]
[[3 2 0]
 [8 2 8]
 [4 3 6]
 [8 5 9]]


In [55]:
# 수직으로 2개씩 자름
r1, r2, r3 = np.hsplit(r, [2,4])
print(r1)
print(r2)
print(r3)

[[8 8]
 [8 8]
 [4 3]
 [9 8]]
[[2 3]
 [3 8]
 [0 4]
 [0 8]]
[[2 0]
 [2 8]
 [3 6]
 [5 9]]


**15) Sort** : 정렬하기

In [56]:
r1 = np.random.randint(10, size=(3,3))
print(r1)

[[0 9 6]
 [5 3 1]
 [8 0 4]]


In [57]:
# 가로로 sorting
r1.sort() # axis -1과 1은 같은 동작을 한다
r1

array([[0, 6, 9],
       [1, 3, 5],
       [0, 4, 8]])

In [58]:
# 세로로 sorting
r1.sort(axis=0) 
r1

array([[0, 3, 5],
       [0, 4, 8],
       [1, 6, 9]])

In [59]:
# 문제
# 1~9까지의 숫자가 들어가는 3*3 행렬을 만드세요
# 만든 행렬을 무작위로 섞으세요

In [60]:
import random

In [63]:
# 3*3 행렬 생성
matrix = np.arange(1,10)
matrix = np.reshape(matrix,(3,3))
np.random.shuffle(matrix)
matrix

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [64]:
ranmatrix = np.hstack(matrix)
random.shuffle(ranmatrix )
ranmatrix.reshape(3,3)

array([[8, 6, 2],
       [9, 5, 1],
       [3, 7, 4]])