### Datatype

- boolean : bool
- integer : int64
- float : float64
- byte String : S24
- unicode String : U24

### 1. Datatype

In [1]:
import numpy as np

#### 1) Boolean (논리형)

In [2]:
na = np.array([True, False])
na.dtype

dtype('bool')

#### 2) Integer (정수형)

In [3]:
na = np.array([1, 2, 3])
na.dtype

dtype('int64')

#### 3) Float (실수형)

In [4]:
na = np.array([1.0, 2.0, 3.0])
na.dtype

dtype('float64')

### 2. Change datatype

In [5]:
na = np.array([-1.0, 0.0, 1.0, 2.2, 3.8])
print(na)

[-1.   0.   1.   2.2  3.8]


#### 1) 숫자형으로 변환

In [6]:
na = na.astype('int64')
print(na)

[-1  0  1  2  3]


#### 2) 논리형으로 변환

In [7]:
na = na.astype('bool') # 0이면 False
print(na) 

[ True False  True  True  True]


#### 3) Byte string으로 변환

In [8]:
na = na.astype('S24')
print(na)

[b'True' b'False' b'True' b'True' b'True']


#### 4) Unicode string으로 변환

In [9]:
na = na.astype('U24')
print(na)

['True' 'False' 'True' 'True' 'True']


ex) 5~10까지 랜덤한 숫자가 들어있는 5*5 행렬

In [10]:
na = np.random.rand(5,5) # 5*5 난수 생성
print(na)

[[0.44885799 0.49228706 0.7629643  0.3424544  0.01770165]
 [0.41356843 0.47816038 0.23024683 0.7863608  0.27639292]
 [0.08588055 0.12272374 0.60638822 0.78769812 0.64946638]
 [0.46907857 0.59380553 0.65611989 0.37041989 0.61156111]
 [0.26640689 0.58235118 0.97747404 0.53229288 0.39388293]]


In [11]:
na = (na*6+5).astype('int64') # 숫자형으로 변환
print(na)

[[ 7  7  9  7  5]
 [ 7  7  6  9  6]
 [ 5  5  8  9  8]
 [ 7  8  8  7  8]
 [ 6  8 10  8  7]]
